# Generated by Django 5.0.1 on 2024-03-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('lot_number', models.CharField(max_length=50)),
                ('image_name', models.CharField(max_length=100)),
                ('image_bytecode', models.BinaryField()),
                ('label_data', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
